### ISSUE TITLE
Dificuldade ao implementar a biblioteca

### ISSUE THREAD

**Issue by casadolog** [vmassuchetto/WebserviceCaixa#1]
Olá, primeiro agradeço pela biblioteca. Ela é muito útil. Estamos com encontrando dificuldades para implementá-la. O erro que estamos recebendo como resposta é o seguinte:

...[COD_RETORNO] => X5
                                    [ORIGEM_RETORNO] => RACF-SPD9CJD2
                                    [MSG_RETORNO] => (RA03) USUARIO NAO AUTORIZADO A EXECUTAR A TRANSACAO.
                                    [DADOS] => Array
                                        (
                                            [EXCECAO] => EXCECAO NO BAR_CONSULTA_COBRANCA_BANCARIA_WS.BAR_CONSULTA_COBRANCA_BANCARIA_SUB.Consulta_Boleto.GCB_PGM. DETALHES: RecoverableException(3) - Funcao: throwableToMbException, Texto Excecao: Error returned from CICS Request, Texto de Insercao(1) - CTG9631E Error occurred during an interaction with CICS: ECI_ERR_SECURITY_ERROR, error code: -27
.RecoverableException(2) - Funcao: requestData, Texto Excecao: Error returned from CICS Request, Texto de Insercao(1) - com.ibm.broker.nodes.cicsnodes.CICSRequestNode : javax.resource.spi.SecurityException: CTG9631E Error occurred during an interaction with CICS: ECI_ERR_SECURITY_ERROR, error code: -27
	at com.ibm.connector2.cics.ECIManagedConnection.checkReturnCode(Unknown Source)...

Você já obteve este mesmo tipo de erro?

Desde já agradeço.

**Comment by vmassuchetto** [comment]
Já vi este erro. Tem algum problema na geração do hash de autenticação, ou a Caixa ainda não liberou o CPF ou CNPJ para consultar o webservice. Veja no manual se as variáveis `CODIGO_BENEFICIARIO` e `NOSSO_NUMERO` estão corretas, tamanho certo e tudo mais. Você pode também ligar no atendimento da Caixa e perguntar se estes códigos estão liberados.

**Comment by casadolog** [comment]
Obrigado

Liguei na caixa 4 vezes, o quarto atendente viu que a havia uma liberação,
mas não era para esse tipo de envio.
Entrei em contato com a gerente, problema resolvido :-)


Em 22 de novembro de 2017 08:19, Vinicius Massuchetto <
notifications@github.com> escreveu:

**Comment by vmassuchetto** [comment]
Que ótimo! Também tive muitas dificuldades. É duro
