### ISSUE TITLE
Exception:  Unable to sendViaPost to url[https://des.barramento.caixa.gov.br/sibar/ConsultaCobrancaBancaria/Boleto]

### ISSUE THREAD

**Issue by lukaz-sampaio** [vmassuchetto/WebserviceCaixa#10]
Bem, estou tentando consumir o serviço com Java, mas está sendo me retornando a seguinte exception: 

```5:45:21 PM org.apache.axis2.transport.http.HTTPSender sendViaPost
INFORMAÇÕES: Unable to sendViaPost to url[https://des.barramento.caixa.gov.br/sibar/ConsultaCobrancaBancaria/Boleto]
org.apache.axis2.AxisFault: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target ```

A minha dúvida é: eu preciso de alguma autorização pra poder consumir o serviço mesmo no ambiente de desenvolvimento?

**Comment by DiegoCSantos** [comment]
Você está utilizando o certificado http do servidor da caixa na requisição?

Sempre que passei por isso ( sun.security.validator.ValidatorException: PKIX ) consumindo API dos bancos o motivo era o certificado.

verifique o link https://stackoverflow.com/questions/21223084/how-do-i-use-an-ssl-client-certificate-with-apache-httpclient

Não sei quanto a necessidade de permissão para utilizar o ambiente de homologação, pois estou aguardando um cliente interessado em usar o API da caixa

**Comment by lukaz-sampaio** [comment]
Não estou usando nenhum certificado. Pelo visto vou ter que falar com o gerente do banco.
Eu achava que só pelo código do beneficiário já era o suficiente, já que pelo e-cobranca eu já consigo emitir boleto.

**Comment by lukaz-sampaio** [comment]
Acessando os links pelo browser é me pedido permissão por causa que é um certificado não confiável.
Quando vou gerar as classes no Java usando o wsdl é me pedido permissão também por causa que diz que é um certificado não confiável.
Nas classes geradas, eu não vi onde usar nenhum certificado.

**Comment by lukaz-sampaio** [comment]
Depois de quebrar a cabea um pouquinho. Cheguei nessa mensagem

> (BK76) ERRO NA FORMATACAO DA MENSAGEM.

Mas não sei qual a solução. Já tentei imprimir o xml montado, mas sem sucesso, só consigo pegar o valor dos atributos;

Esse erro é na formtação do meu envio ou no de resposta?

**Comment by vmassuchetto** [comment]
@lukaz-sampaio esse erro acontece quando há algum parâmetro faltando na consulta. Por exemplo, se não constar `CODIGO_BENEFICIARIO` ou `NOSSO_NUMERO`.

**Comment by lukaz-sampaio** [comment]
Era a versão da biblioteca. Quando mudei a versão da biblioteca a mensagem mudou para:

> (35) BENEFICIARIO INFORMADO NAO CADASTRADO

Creio que agora o próximo passo seja pedir acesso ao webservice de teste.
