### ISSUE TITLE
Erro no Tipo de Juros e Multa

### ISSUE THREAD

**Issue by mariojorge** [vmassuchetto/WebserviceCaixa#12]
Boa tarde. 

Estou tendo problemas de estrutura no tipo de Juros e Multa como segue em anexo.

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <manutencaocobrancabancaria:SERVICO_SAIDA xmlns:manutencaocobrancabancaria="http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo" xmlns:sibar_base="http://caixa.gov.br/sibar">
         <sibar_base:HEADER>
            <VERSAO>1.0</VERSAO>
            <OPERACAO>INCLUI_BOLETO</OPERACAO>
            <DATA_HORA>20180426154223</DATA_HORA>
         </sibar_base:HEADER>
         <COD_RETORNO>X5</COD_RETORNO>
         <ORIGEM_RETORNO>BROKER-SPD9CJD2</ORIGEM_RETORNO>
         <MSG_RETORNO>(BK76) ERRO NA FORMATACAO DA MENSAGEM.</MSG_RETORNO>
         <DADOS>
            <EXCECAO>EXCECAO NO BAR_MANUTENCAO_COBRANCA_BANCARIA_WS.SOAPInput_Empresas_Externas. DETALHES: ParserException(1) - Funcao: ImbDataFlowNode::createExceptionList, Texto Excecao: Node throwing exception, Texto de Insercao(1) - BAR_MANUTENCAO_COBRANCA_BANCARIA_WS.SOAPInput_Empresas_Externas.ParserException(2) - Funcao: ImbSOAPInputNode::validateData, Texto Excecao: Error occurred in ImbSOAPInputHelper::validateSOAPInput(), Texto de Insercao(1) - BAR_MANUTENCAO_COBRANCA_BANCARIA_WS.SOAPInput_Empresas_Externas.ParserException(3) - Funcao: ImbRootParser::parseNextItem, Texto Excecao: Exception whilst parsing.ParserException(4) - Funcao: ImbSOAPParser::createSoapShapedTree, Texto Excecao: problem creating SOAP tree from bitstream.ParserException(5) - Funcao: ImbXMLNSCParser::parseLastChild, Texto Excecao: XML Parsing Errors have occurred.ParserException(6) - Funcao: ImbXMLNSCDocHandler::handleParseErrors, Texto Excecao: A schema validation error has occurred while parsing the XML document, Texto de Insercao(1) - 6012, Texto de Insercao(2) - 1, Texto de Insercao(3) - 28, Texto de Insercao(4) - 43, Texto de Insercao(5) - cvc-enumeration-valid: The value "﻿﻿ISENTO" is not valid with respect to the enumeration facet for type "#Anonymous". It must be a value from the enumeration., Texto de Insercao(6) - /XMLNSC/{http://schemas.xmlsoap.org/soap/envelope/}:Envelope/{http://schemas.xmlsoap.org/soap/envelope/}:Body/{http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo}:SERVICO_ENTRADA/DADOS/INCLUI_BOLETO/TITULO/JUROS_MORA/TIPO.</EXCECAO>
         </DADOS>
      </manutencaocobrancabancaria:SERVICO_SAIDA>
   </soapenv:Body>
</soapenv:Envelope>`

Os dados que estou enviando são os seguintes.

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ext="http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo" xmlns:sib="http://caixa.gov.br/sibar">
   <soapenv:Header/>
   <soapenv:Body>
      <ext:SERVICO_ENTRADA>
         <sib:HEADER>
            <VERSAO>1.2</VERSAO>
            <AUTENTICACAO>gAIIAbd0LjtgRAy5mDLc68t2/Kx0HLb8M9fWdYmY/rQ</AUTENTICACAO>
            <USUARIO_SERVICO>SGCBS01D</USUARIO_SERVICO>
            <OPERACAO>INCLUI_BOLETO</OPERACAO>
            <SISTEMA_ORIGEM>SIGCB</SISTEMA_ORIGEM>
            <UNIDADE>0743</UNIDADE>
            <DATA_HORA>20180419093300</DATA_HORA>
            <ID_PROCESSO>11967</ID_PROCESSO>
         </sib:HEADER>
         <DADOS>
            
            <INCLUI_BOLETO>
               <CODIGO_BENEFICIARIO>00011967</CODIGO_BENEFICIARIO>
               <TITULO>
                  
                  <NOSSO_NUMERO>9000257835000006</NOSSO_NUMERO>
                  <NUMERO_DOCUMENTO>25783500000</NUMERO_DOCUMENTO>
                  <DATA_VENCIMENTO>2018-04-30</DATA_VENCIMENTO>
                  <VALOR>73.36</VALOR>
                  <TIPO_ESPECIE>99</TIPO_ESPECIE>
                  <FLAG_ACEITE>S</FLAG_ACEITE>
                  <JUROS_MORA>
                     <TIPO>﻿﻿ISENTO</TIPO>
                     <VALOR>0.00</VALOR>
                  </JUROS_MORA>
                  <POS_VENCIMENTO>
                     <ACAO>﻿DEVOLVER</ACAO>
                     <NUMERO_DIAS>999</NUMERO_DIAS>
                  </POS_VENCIMENTO>
                  <CODIGO_MOEDA>09</CODIGO_MOEDA>
                  <PAGADOR>
                     
                     <CPF>69574529304</CPF>
                     <NOME>IRAN GOMES RIBEIRO</NOME>
                     
                     <ENDERECO>
                        <LOGRADOURO>VIL SAO CRISTOVAO, 896</LOGRADOURO>
                        <BAIRRO>FARIAS BRITO</BAIRRO>
                        <CIDADE>ARACATI</CIDADE>
                        <UF>CE</UF>
                        <CEP>62800000</CEP>
                     </ENDERECO>
                  </PAGADOR>
                  <MULTA>
                     <DATA>2018-04-30</DATA>
                     
                     <VALOR>6.27</VALOR>
                  </MULTA>
                  <VALOR_IOF>0.00</VALOR_IOF>
                  <FICHA_COMPENSACAO>
                     <MENSAGENS>
                        
                        <MENSAGEM>BOLETO TESTE MSG FICHA</MENSAGEM>
                     </MENSAGENS>
                  </FICHA_COMPENSACAO>
                  
                  <RECIBO_PAGADOR>
                     <MENSAGENS>
                        
                        <MENSAGEM>BOLETO TESTE MSG PAGADOR</MENSAGEM>
                     </MENSAGENS>
                  </RECIBO_PAGADOR>
                  
                  <PAGAMENTO>
                     <QUANTIDADE_PERMITIDA>1</QUANTIDADE_PERMITIDA>
                     <TIPO>﻿NÃO_ACEITA_VALOR_DIVERGENTE</TIPO>
                     
                     <VALOR_MINIMO>0.00</VALOR_MINIMO>
                     <VALOR_MAXIMO>0.00</VALOR_MAXIMO>
                  </PAGAMENTO>
               </TITULO>
            </INCLUI_BOLETO>
         </DADOS>
      </ext:SERVICO_ENTRADA>
   </soapenv:Body>
</soapenv:Envelope>`

Já tentei as 3 opções conforme documentação, mas nenhuma delas da certo.

Alguém já passou por isso?

**Comment by vmassuchetto** [comment]
Tem dois bytes inválidos antes do valor `ISENTO`. Veja no final da mensagem.

    The value "  ﻿﻿ISENTO" is not valid with respect to the enumeration facet for type "#Anonymous".

Escrevi sobre [como ler estas mensagens de erro](https://github.com/vmassuchetto/WebserviceCaixa/blob/master/README.md#mensagens-de-erro) usando este exemplo.

**Comment by mariojorge** [comment]
Estranho pq está preenchido assim

`<JUROS_MORA><TIPO>﻿﻿ISENTO</TIPO><VALOR>0.00</VALOR></JUROS_MORA>`

**Comment by vmassuchetto** [comment]
Mas tem algo de errado com ele. Tente omitir toda esta parte da requisição, porque se o juros é "0", se não me engano, não tem porque passar ele.

**Comment by mariojorge** [comment]
Eu apaguei os textos e digitei novamente com os mesmos dados e passou, você tinha razão, só não sei como isso apareceu para você mas pra mim não aparecia. Grato.
