### ISSUE TITLE
Implementação no sistema WHMCS

### ISSUE THREAD

**Issue by pageupsolutions** [vmassuchetto/WebserviceCaixa#14]
Olá, gostaria de 2 informações:
Essa biblioteca pode ser implementada no sistema WHMCS, se sim como poderia fazer?
Verifiquei que você trata a geração somente para CNPJ, sou pessoa física e possuo contrato com a CEF para geração de boletos SIGCB, essa biblioteca serviria para mim pessoa física?

**Comment by vmassuchetto** [comment]
@pageupsolutions a biblioteca não tem integração com nenhum outro sistema. Você vai ter que desenvolver você mesmo.

- Se este sistema for em PHP, é possível importá-la no código e realizar as chamadas conforme explicado no `README.md`.
- Se este sistema não for PHP, você vai precisar de um servidor PHP para realizar as chamadas e adaptar o seu sistema para chamar o PHP via HTTP ou algum outro método que você ache mais adequado.

A biblioteca suporta a criação da cobrança registrada tanto para CPFs quanto CNPJs. Verifique no [manual da caixa](doc/MO38239.pdf) como montar a requisição para cada caso.

Vou fechar esta dúvida. Se você tiver outra mais específica é só abrir novamente. Abs.
