### ISSUE TITLE
(BK76) ERRO NA FORMATACAO DA MENSAGEM.

### ISSUE THREAD

**Issue by bartolomeukuma** [vmassuchetto/WebserviceCaixa#15]
Boa tarde a todos... eu estou apanhando um bocado aqui... tentando de alguma forma fazer a consulta de um boleto... mas ta difícil... pra cada teste surge um zilhão de novos erros.
estou tentando fazer um post utilizando o Postman, mas por algum motivo nem mesmo o exemplo presente no manual da caixa está passando. entrei em contato com a caixa e escutei deles que a caixa não da suporte, que meu único auxiliador seria o manual.
minha ultima msg de erro. eh uma excessao dizendo que o método consulta_boleto não eh um método permitido... alguém pode por favor dar uma luz pra este newby?

**Comment by bartolomeukuma** [comment]
Consegui fazendo da seguinte maneira...
```
$header = new stdClass();
$header->VERSAO = "1.0";
$header->AUTENTICACAO = $autenticacao;
$header->USUARIO_SERVICO = "SGCBS02P";
$header->OPERACAO = "CONSULTA_BOLETO";
$header->SISTEMA_ORIGEM ="SIGCB";
$header->DATA_HORA = $data_hora;
$soapHeader = new SoapVar($header, SOAP_ENC_OBJECT, null, null, 'HEADER', 'http://caixa.gov.br/sibar');
$param->HEADER = $soapHeader;

```
e o corpo de dados... montei da mesma forma...
```
$dados = new stdClass();
$dados->CONSULTA_BOLETO = new stdClass();
$dados->CONSULTA_BOLETO->CODIGO_BENEFICIARIO = $dados['cedente'];
$dados->CONSULTA_BOLETO->NOSSO_NUMERO = $dados['nosso_numero'];
$soapDados = new SoapVar($dados, SOAP_ENC_OBJECT, null, null, 'DADOS');
$param->DADOS = $soapDados;
```

depois disso... uso o soapCliente para enviar a request.
```
$client = new SoapClient("https://barramento.caixa.gov.br/sibar/ConsultaCobrancaBancaria/Boleto?wsdl");
$result = $client->CONSULTA_BOLETO($param);
```

dessa maneira consegui realizar a consulta... estou agora trabalhando nos outros métodos.
obrigado pela ajuda

**Comment by vmassuchetto** [comment]
Ficou bem mais limpo. De fato vale mais a pena implementar dessa maneira do que usando bibliotecas velhas.

Não tenho mais trabalhado com os boletos, mas seria bem legal disponibilizar pras pessoas uma interface fácil de usar pra que não tivéssemos tanto problema com esse serviço. É possível simplesmente utilizar desta forma que você fez e chamar um cliente que refaz essa rotina de acordo com um arquivo de configuração. Obrigado por compartilhar a solução.

**Comment by bartolomeukuma** [comment]
eu tenho aqui o arquivo que estou criando pra usar no sistema da empresa...
quando sobrar um tempo eu crio uma interface com os metodos de incluir, baixar, alterar e consultar... ai disponibilizo pra comunidade.
