### ISSUE TITLE
Cancelamento de Boleto Registrado WebserviceCaixa

### ISSUE THREAD

**Issue by Wendool** [vmassuchetto/WebserviceCaixa#16]
Boa tarde, 
Estou com problemas para cancelamento(Baixa_Boleto) de títulos sem utilização quando desejado, sempre apresentando o seguinte erro, alguém conseguiu resolver?

**Informações repassadas**
	$arrayDadosHash = array(
				'codigoCedente' => $informacoes['codigoCedente'],
				'nossoNumero' => $informacoes['nossoNumero'],
				'dataVencimento' => $informacoes['dataVencimento'],
				'valorNominal' => $informacoes['valorNominal'],
				'cnpj' => $informacoes['cnpj']
		);

$arrayDados = array(
				'soapenv:Body' => array(
					'manutencaocobrancabancaria:SERVICO_ENTRADA' => array(
						'sibar_base:HEADER' => array(
								'VERSAO' => '1.0',
								'AUTENTICACAO' => $autenticacao,
								'USUARIO_SERVICO' => 'SGCBS02P', 
								'OPERACAO' => 'BAIXA_BOLETO', 
								'SISTEMA_ORIGEM' => 'SIGCB',
								'UNIDADE' => $informacoes['numeroAgencia'],
								'DATA_HORA' => date('YmdHis')
						),
						'DADOS' => array(
								'BAIXA_BOLETO' => array(
										'CODIGO_BENEFICIARIO' => $informacoes['codigoCedente'],
										'NOSSO_NUMERO' => $informacoes['nossoNumero'], 			
								)
						)
					)
				)
		);

**Resultado**
Array
(
    [CONTROLE_NEGOCIAL] => Array
        (
            [ORIGEM_RETORNO] => SIGCB
            [COD_RETORNO] => 1
            [MENSAGENS] => Array
                (
                    [RETORNO] => (54) OPERACAO NAO PERMITIDA - HASH DIVERGENTE
                )

        )

)

**Comment by Wendool** [comment]
Olá @vmassuchetto, obrigado pelo contato, estranho utilizo a mesma forma para gerar remessa, editar remessa apenas cancelar esta com essa situação, qual suporte 0800 da caixa? Nunca consegui auxilio deles, não sabem de nada, possui um contato especifico que passa tirar essas duvida com o código fonte?

**Comment by vmassuchetto** [comment]
Não tenho contato específico. Sugiro ver se a operação está liberada para a
conta.

Em ter, 13 de nov de 2018 10:18, Wendool <notifications@github.com>
escreveu:

**Comment by vmassuchetto** [comment]
Fechando por aqui. Caso tenha problemas é só reabrir.

**Comment by fagnerdireito** [comment]
Eu estava com o mesmo problema, mas lendo o manual percebi que temos que enviar a o valor=0; (zero) e a data de vencimento também com zeros.
Mas na api... para que a data fique com zeros basta você não informar ela que a função de hash faz o seu papel e prontinho... tudo deu certo por aqui, a baixa foi realizada com sucesso.
