### ISSUE TITLE
Erro ao implementar o web service

### ISSUE THREAD

**Issue by zezekaka** [vmassuchetto/WebserviceCaixa#18]
Bom, segui os passos do readme e o erro foi o seguinte

![captura de tela 2019-01-08 as 22 35 52](https://user-images.githubusercontent.com/35896719/50868252-c6549e80-1395-11e9-8c61-a6f7cd88dade.png)

E aqui, o código, eu simplesmente peguei a definição dos dois arrays ( O emissor e o novo_boleto) e os coloquei em meu template, declarando o WebserviceCaixa.php

![captura de tela 2019-01-08 as 22 49 38](https://user-images.githubusercontent.com/35896719/50868672-b76eeb80-1397-11e9-87b4-500d82c18937.png)
-------------------------------
Onde eu faço a indexação dos wsdl disponibilizado pela Caixa? Eu preciso fazer algum "server.php" ou algo do tipo? Se sim como?

**Comment by vmassuchetto** [comment]
Oi @zezekaka . Qual versão do PHP está usando? Os warnings não deveriam acontecer porque o `ConfigPadrao.php` ou o seu `Config.php` devem ser inseridos, e não os dois. Acho que chegamos em um problema de compatibilidade do nusoap.

**Comment by zezekaka** [comment]
Putz, pode ser a versão do PHP mesmo, como dito, segui seu tutorial e so usei a configuração padrão (no caso o arquivo ConfigPadrao.php), vou testar com o PHP 5 e ver o que acontece, e sobre os arquivos WSDL de manutenção e consulta que a caixa me disponibilizou?

**Comment by vmassuchetto** [comment]
Esta nova versão já acessa o WSDL diretamente da Caixa. Não deve dar problema em relação a isso.

**Comment by vmassuchetto** [comment]
Que bom que deu certo.

Não conheço os arquivos `.rem`. Pelo menos não precisei deles pra fazer a implementação. Vi que a Caixa retirou o link para o manual dos webservices, e o que existe sobre cobrança registrada no site da Caixa agora parece ser esta referência que você está seguindo que cita os arquivos `.rem`.

Não sei qual a referência correta, você tem como saber?

O manual que foi seguido para a biblioteca é [este daqui](https://github.com/vmassuchetto/WebserviceCaixa/raw/0b27c24d78f5ccc25fd0badf238f16c1c91a012f/doc/MO38239.pdf), que foi apagado porque coloquei o link no `README`, mas agora está indisponível como falei.

**Comment by josemarcam** [comment]
Então, o que eu estava lendo para estudar a respeito, é sobre layout de arquivos cnab que vo linkar aqui.

- [Manual cnab 240](https://github.com/vmassuchetto/WebserviceCaixa/files/2749163/Manual_Leiaute_CNAB240_SIGCB.pdf)
- [Manual cnab 400](https://github.com/vmassuchetto/WebserviceCaixa/files/2749170/Manual_Leiaute_CNAB400_SIGCB.pdf)


Sobre o arquivo de remessa. Os clientes que usarão o meu serviço de registro de boletos, farão upload deste arquivo de `.rem`, que contem as informações do cedente e do sacado (as mesmas informações que são exigidas no array do web service), mas esse arquivo vem assim

![captura de tela 2019-01-11 as 08 08 15](https://user-images.githubusercontent.com/35896719/51027461-0ffcdf00-1578-11e9-923f-fdf1eaa31079.png)
(Em formato cnab240)

Nesse arquivo, tenho as informações necessárias pra gerar um `$emisso` e também um `$novo_boleto`.O que eu quero fazer é o seguinte, quando o cliente faz o upload desse arquivo, eu o organizo e transformo em xml, possibilitando assim criar um código php para o preenchimento automático dos campo necessários para fazer todo o CRUD do web service. Minha dificuldade é transformar isso em xml e separar cada informação em uma chave. Será que da?

**Comment by vmassuchetto** [comment]
Agora acho que entendi. É possível mas esta lib aqui não vai ajudar nessa parte.

Você pode ler o arquivo e iterar em cada linha fazendo o parse das posições e transformando nos parâmetros necessários dos métodos `Inclui`, `Altera`, etc.

**Comment by vmassuchetto** [comment]
@zezekaka se estiver tudo certo vamos fechar aqui. Se precisar de algo mais siga perguntando. Abs.
