### ISSUE TITLE
Erro (java.lang.IllegalArgumentException)

### ISSUE THREAD

**Issue by josemarcam** [vmassuchetto/WebserviceCaixa#19]
Então, eu nao sei oque acontece aqui:
![captura de tela 2019-01-19 as 01 11 53](https://user-images.githubusercontent.com/35896719/51421622-dcc5db80-1b87-11e9-9ce1-f1fa38881230.png)

Se eu não me engano, isso é erro de conversão de alguma variável né, mas quando eu fui fazer a conversão no php, eu percebi que nos arrays tem apenas strings, então não tenho a mínima ideia de oque pode ser, acho que isso pode ajudar também:
![captura de tela 2019-01-19 as 01 22 19](https://user-images.githubusercontent.com/35896719/51421664-af2d6200-1b88-11e9-932b-1c2dc606916c.png)

**Comment by vmassuchetto** [comment]
Seria melhor copiar e colar o código ao invés de enviar prints.

O erro é sobre algum campo decimal, possivelmente o valor, que deve estar no formato `0.00`.

**Comment by josemarcam** [comment]
Resolvido, o problema pelo que eu confirmei com um cliente, é que os boletos não são computados depois das 20h, então quando eu clicava no link para download do boleto, eu obtinha esse erro pois eu tinha gerado ele depois das 20h. Bom pelo menos foi isso que eu encontrei pra explicar esse erro, fiz uns testes em horários diferentes, e deu positivo para a minha hipótese!
