### ISSUE TITLE
Serviço insdiponível

### ISSUE THREAD

**Issue by wagnermengue** [vmassuchetto/WebserviceCaixa#2]
Olá, 

Fiz a implementação, ajustei alguns itens mas sempre recebo o mesmo erro no final:

`O sistema de boletos da Caixa Econômica Federal encontra-se indisponível. Tente acessar o link mais tarde.`

Alguma forma de saber se é alguma configuração? Ou o serviço está fora mesmo?

Outra coisa, lendo no manual vi que eles pedem para que seja realizado um post com os dados para realizar a inclusão do título por exemplo. Mas nessa solução trabalha-se com um webservice SOAP. A CEF tem a integração com os 2 métodos?
Att,

**Comment by vmassuchetto** [comment]
[Veja aqui como debugar](https://github.com/vmassuchetto/WebserviceCaixa#debug).

Adicione `DEBUG=<hash do começo do arquivo>` à requisição para ter o relatório completo do que foi feito. Pode ser algum problema de campo rejeitado, acentos ou algo parecido.

Porém, das 18h de antes de ontem (28/11) até as 11h de ontem (29/11) o serviço estava de fato indisponível e foi um deus nos acuda.

**Comment by vmassuchetto** [comment]
@wagnermengue não entendi. Quais dois métodos? A requisições SOAP foi a única que tive contato por ora.

**Comment by wagnermengue** [comment]
@vmassuchetto os 2 métodos (integração) seriam via client SOAP ou via post REST que eu quiz informar. Aqui montei um XML simples com os dados e realizei um POST com cURL para a url informada por você aqui, somente assim consegui receber um retorno "meio" tratado do banco. Caso seja necessário tentarei novamente com seus fontes, qualquer coisa posto aqui.

De qualquer forma obrigado. o/

**Comment by vmassuchetto** [comment]
Não tive contato com a API REST. Tenta o debugador que ele vai mostrar o que está acontecendo. Boa sorte!

**Comment by r-guimaraes** [comment]
@wagnermengue e @vmassuchetto Estou tentando também apenas enviar uma requisição de consulta de boleto para teste, e recebo sempre este erro, quando utilizo o debug:

                            [ERRO] => operation CONSULTA_BOLETO not present in WSDL.
Já passaram por isso? Sabem o que pode ser?

Valeu!

**Comment by wagnermengue** [comment]
@r-guimaraes acabei não utilizando o sistema de consultas da caixa.

**Comment by vmassuchetto** [comment]
@r-guimaraes o WSDL pra configurar a conexão é o de consulta? Seria [este daqui](https://des.barramento.caixa.gov.br/sibar/ConsultaCobrancaBancaria/Boleto?wsdl). Nele tem o que precisa pra requisição funcionar:

```xml
<wsdl:operation name="CONSULTA_BOLETO">
```
