### ISSUE TITLE
Alterar um boleto ja cadastrado

### ISSUE THREAD

**Issue by josemarcam** [vmassuchetto/WebserviceCaixa#21]
Estou com duvidas na execução da função alterar do web service, alguém teria um exemplo de execução dessa função?

**Comment by vmassuchetto** [comment]
@zezekaka embora não tenha um exemplo no [arquivo de exemplo](https://github.com/vmassuchetto/WebserviceCaixa/blob/master/Exemplo.php) (contribuições são bem-vindas), deve-se seguir os parâmetros obrigatórios do [manual da CEF](https://github.com/vmassuchetto/WebserviceCaixa/raw/0b27c24d78f5ccc25fd0badf238f16c1c91a012f/doc/MO38239.pdf) (manual antigo, o link para o atual deixou de funcionar).

Veja a página 14 e a coluna "Obrigatório". Construa um array com estes parâmetros e chame algo como:

```php
$ws = new WebserviceCaixa($emissor);
$ws->Altera($parametros)
```
