### ISSUE TITLE
Erro 405 - Consulta Boleto

### ISSUE THREAD

**Issue by ezinhani** [vmassuchetto/WebserviceCaixa#23]
Warning: wsdl error: Getting https://barramento.caixa.gov.br/sibar/ConsultaCobrancaBancaria/Boleto/Externo?wsdl - HTTP ERROR: Unsupported HTTP response status 405 Method Not Allowed (soapclient->response has contents of the response) in /WebserviceCaixa/WebserviceCaixa.php:170

**Problema resolvido:**
Inserir 'IDENTIFICADOR_ORIGEM' no método de consulta

**Comment by fagnerdireito** [comment]
Olá, estou com o mesmo problema, coloquei o identificador de origem mas ainda persiste o problema, você teve que ajustar alguma outra coisa?

erro reportado:
`[error_str] => wsdl error: Getting https://barramento.caixa.gov.br/sibar/ConsultaCobrancaBancaria/Boleto/Externo?wsdl - HTTP ERROR: Unsupported HTTP response status 405 Method Not Allowed (soapclient->response has contents of the response)`

meu array de saída:

> Array
> (
>     [CNPJ] => 00000000000000
>     [CODIGO_BENEFICIARIO] => 000000
>     [IDENTIFICACAO] => NOME DA EMPRESA
>     [ENDERECO1] => RUA 03
>     [ENDERECO2] => MINEIROS - GO
>     [UNIDADE] => 0000
>     [IDENTIFICADOR_ORIGEM] => 000.0.000.000
>     [NOSSO_NUMERO] => 14000000000093546
>     [NUMERO_DOCUMENTO] => 000093546
> )
>

**Comment by fagnerdireito** [comment]
**Problema resolvido**: Eu apenas removi da url a palavra **EXTERNO**, no arquivo WebserviceCaixa.php.

de:
`$this->wsdl_consulta = $base_url . '/sibar/ConsultaCobrancaBancaria/Boleto/Externo?wsdl';`

para:
`$this->wsdl_consulta = $base_url . '/sibar/ConsultaCobrancaBancaria/Boleto?wsdl';`
