### ISSUE TITLE
Erro SSL

### ISSUE THREAD

**Issue by wkarita** [vmassuchetto/WebserviceCaixa#3]
Boa tarde!

Estou implantando o sistema e estou como seguinte erro:

[ERRO] => wsdl error: Getting https://barramento.caixa.gov.br/sibar/ConsultaCobrancaBancaria/Boleto?xsd=xsd0 - HTTP ERROR: cURL ERROR: 35: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
url: https://barramento.caixa.gov.br:443/sibar/ConsultaCobrancaBancaria/Boleto?xsd=xsd0

Poderia me ajudar a resolver esse erro?

Grato,

Wilson

**Comment by vmassuchetto** [comment]
Oi Wilson. Ou você usa o certificado que a CEF forneceu, ou você faz uma [conexão insegura](https://github.com/vmassuchetto/WebserviceCaixa/blob/master/WebserviceCaixa.php#L154).

Tem outros motivos também do porquê que isso pode acontecer. A porta 443 está aberta? Você sabe a versão do seu SSL? Coloque a saída destes comandos aqui:

    curl  https://barramento.caixa.gov.br/sibar/ConsultaCobrancaBancaria/Boleto?xsd=xsd0 --verbose --no-check-certificate
    curl  https://barramento.caixa.gov.br/sibar/ConsultaCobrancaBancaria/Boleto?xsd=xsd0 --verbose --sslv2

**Comment by vmassuchetto** [comment]
Fechando por enquanto @wkarita , avise aí se tiver problemas.
