### ISSUE TITLE
erro no php7

### ISSUE THREAD

**Issue by rltc2** [vmassuchetto/WebserviceCaixa#4]
Bom dia.
Estou tentando implantar este código do WebService da Caixa com php7 e estou obtendo os avisos listados abaixo (após a linha tracejada).
Até tentei usar o __construct para construir a classe mas aí obtenho outros problemas.
Vc poderia me ajudar falando que caminho seguir para solução?
Obrigada
------------------------------------

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; nusoap_base has a deprecated constructor in /home/storage/a/cd/b8/trt15eventos/public_html/WebserviceCaixa/lib/nusoap/lib/nusoap.php on line 85

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; nusoap_fault has a deprecated constructor in /home/storage/a/cd/b8/trt15eventos/public_html/WebserviceCaixa/lib/nusoap/lib/nusoap.php on line 1007

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; nusoap_xmlschema has a deprecated constructor in /home/storage/a/cd/b8/trt15eventos/public_html/WebserviceCaixa/lib/nusoap/lib/nusoap.php on line 1095

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; soapval has a deprecated constructor in /home/storage/a/cd/b8/trt15eventos/public_html/WebserviceCaixa/lib/nusoap/lib/nusoap.php on line 2067

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; soap_transport_http has a deprecated constructor in /home/storage/a/cd/b8/trt15eventos/public_html/WebserviceCaixa/lib/nusoap/lib/nusoap.php on line 2169

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; nusoap_server has a deprecated constructor in /home/storage/a/cd/b8/trt15eventos/public_html/WebserviceCaixa/lib/nusoap/lib/nusoap.php on line 3474

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; wsdl has a deprecated constructor in /home/storage/a/cd/b8/trt15eventos/public_html/WebserviceCaixa/lib/nusoap/lib/nusoap.php on line 4597

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; nusoap_parser has a deprecated constructor in /home/storage/a/cd/b8/trt15eventos/public_html/WebserviceCaixa/lib/nusoap/lib/nusoap.php on line 6533

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; nusoap_client has a deprecated constructor in /home/storage/a/cd/b8/trt15eventos/public_html/WebserviceCaixa/lib/nusoap/lib/nusoap.php on line 7184

Warning: curl_setopt() expects parameter 2 to be integer, string given in /home/storage/a/cd/b8/trt15eventos/public_html/WebserviceCaixa/lib/nusoap/lib/nusoap.php on line 2237

**Comment by vmassuchetto** [comment]
Oi @rltc2 , o serviço foi feito para PHP 5.1 e usa um NuSOAP que é uma tristeza de velho, eu sei, mas não teve jeito. Você pode:

1. incluir uma [versão compatível com PHP 7 do NuSOAP](https://github.com/codecasts/nusoap-php7) no [lugar desta que está sendo utilizada](https://github.com/vmassuchetto/WebserviceCaixa/blob/master/WebserviceCaixa.php#L37), ou;
2. desabilitar os warnings logo antes de incluir a biblioteca:

    error_reporting( E_ALL ^ ( E_NOTICE | E_WARNING | E_DEPRECATED ) );

A opção 1 é melhor mas pode dar mais trabalho.

Vê se funciona aí e avisa.

**Comment by vmassuchetto** [comment]
@rltc2 vou fechar aqui mas se tiver mais problemas coloque aí. Boa sorte.
