### ISSUE TITLE
Usuário não autorizado

### ISSUE THREAD

**Issue by tiagojoelbackes** [vmassuchetto/WebserviceCaixa#5]
Boa tarde!
Estou tentando implementar a integração com a caixa usando esse projeto, porém o servidor fica me enviando o seguinte retorno.

`<COD_RETORNO>X5</COD_RETORNO>
			<ORIGEM_RETORNO>RACF-SPD9CJD2</ORIGEM_RETORNO>
			<MSG_RETORNO>(RA03) USUARIO NAO AUTORIZADO A EXECUTAR A TRANSACAO.</MSG_RETORNO>
			<DADOS>
				<EXCECAO>
EXCECAO NO BAR_CONSULTA_COBRANCA_BANCARIA_WS.BAR_CONSULTA_COBRANCA_BANCARIA_SUB.Consulta_Boleto.GCB_PGM. 
DETALHES: RecoverableException(3) - Funcao: throwableToMbException, 
	Texto Excecao: Error returned from CICS Request, Texto de Insercao(1) - CTG9631E Error occurred during an interaction with CICS: ECI_ERR_SECURITY_ERROR, error code: -27
.RecoverableException(2) - Funcao: requestData, Texto Excecao: Error returned from CICS Request, Texto de Insercao(1) - com.ibm.broker.nodes.cicsnodes.CICSRequestNode : javax.resource.spi.SecurityException: CTG9631E Error occurred during an interaction with CICS: ECI_ERR_SECURITY_ERROR, error code: -27
	at com.ibm.connector2.cics.ECIManagedConnection.checkReturnCode(Unknown Source)
	at com.ibm.connector2.cics.ECIManagedConnection.call(Unknown Source)
	at com.ibm.connector2.cics.ECIConnection.call(Unknown Source)
	at com.ibm.connector2.cics.ECIInteraction.execute(Unknown Source)
	at com.ibm.broker.cics.CICSAdapter.callCICS(CICSAdapter.java:295)
	at com.ibm.broker.nodes.cicsnodes.CICSRequestBaseNode.requestData(CICSRequestBaseNode.java:480)
	at com.ibm.broker.plugin.MbRequestTemplateNode.requestData(MbRequestTemplateNode.java:58)
	at com.ibm.broker.plugin.MbOutputTerminal._propagate(Native Method)
	at com.ibm.broker.plugin.MbOutputTerminal.propagate(MbOutputTerminal.java:133)
	at com.ibm.broker.plugin.MbOutputTerminal.propagate(MbOutputTerminal.java:88)
	at com.ibm.broker.jdbcnodes.RouteNode.evaluate(RouteNode.java:262)
	at com.ibm.broker.plugin.MbNode.evaluate(MbNode.java:1452)
	at com.ibm.broker.plugin.MbOutputTerminal._propagate(Native Method)
	at com.ibm.broker.plugin.MbOutputTerminal.propagate(MbOutputTerminal.java:133)
	at com.ibm.broker.plugin.MbOutputTerminal.propagate(MbOutputTerminal.java:88)
	at com.ibm.broker.soap.SoapExtractNode.evaluate(SoapExtractNode.java:277)
	at com.ibm.broker.plugin.MbNode.evaluate(MbNode.java:1452)
.RecoverableException(1) - Funcao: ImbDataFlowNode::createExceptionList, Texto Excecao: Node throwing exception, Texto de Insercao(1) - BAR_CONSULTA_COBRANCA_BANCARIA_WS.BAR_CONSULTA_COBRANCA_BANCARIA_SUB.Consulta_Boleto.GCB_PGM.
				</EXCECAO>
			</DADOS>`

Não encontrei solução para a resposta ser "(RA03) USUARIO NAO AUTORIZADO A EXECUTAR A TRANSACAO.". Em contato com minha agência da caixa me confirmaram que estou habilitado a utilizar o webservice.

Qualquer ajuda será bem vinda. Desde já agradeço.

**Comment by wagnermengue** [comment]
Olá @tiagojoelbackes eu tive esse problema, porque o meu cliente já estava com o ambiente em produção, e segundo a caixa eles não podem voltar de produção para teste o cliente (nem tem um ambiente de produção) logo, faça um teste sem o des. na frente da url, no caso use a mesma url sem o subdomínio des

**Comment by tiagojoelbackes** [comment]
Era isso mesmo! Funcionou! Obrigado.
Agora é ir atrás dos outros erros ((47) NOSSO NUMERO NAO CADASTRADO PARA O BENEFICIARIO) hehehe.
Fico pensando como que irei fazer o desenvolvimento agora, só batendo em produção.
Me diz uma coisa, em que sistema da caixa posso consultar as cobranças que estão registradas?

**Comment by wagnermengue** [comment]
Show! @tiagojoelbackes não saberia lhe dizer, pois quem faz essas consultas é o próprio cliente por um sistema que desconheço.

**Comment by vmassuchetto** [comment]
@tiagojoelbackes , encontrei estes erros nas seguintes situações:

* `(RA03) USUARIO NAO AUTORIZADO A EXECUTAR A TRANSACAO` quando tem erro na geração do hash de autenticação;
* `(47) NOSSO NUMERO NAO CADASTRADO PARA O BENEFICIARIO` quando o hash está correto mas as consultas ao webservice ainda não foram liberadas para o convênio, é preciso entrar em contato com o suporte.

Para desenvolvimento o único jeito que encontrei foi usar os [endpoints WSDL que iniciam com `des`](https://github.com/vmassuchetto/WebserviceCaixa#modo-de-uso).

A base de consultas do webservice é a mesma do sistema [e-Cobrança](https://ecobranca.caixa.gov.br/). Você pode acompanhar se as operações do webservice estão corretas neste sistema buscando pelos títulos em "Banco de títulos > Consulta de títulos". Deixe o formulário em branco e clique em "Consultar" para exibir todos os títulos.

![consulta-titulos](https://user-images.githubusercontent.com/814115/34558817-6f87d21a-f137-11e7-9b4d-54332a394ca8.png)

Vou fechar aqui mas se tiver mais problemas pergunta aí.

Boa sorte. Sempre é preciso com esse webservice. 😄

**Comment by tiagojoelbackes** [comment]
Olá. Pessoal muito obrigado pela ajuda que estão me dando.
A resposta `(47) NOSSO NUMERO NAO CADASTRADO PARA O BENEFICIARIO` que estou tento é da consulta que ele realiza antes de incluir para ver se já não existe essa cobrança, então entendo que devo ter esse retorno mesmo, já que ela de fato não existe.

Porém quando é realizada a requisição que INCLUI_BOLETO o debug está me retornando o seguinte:

`[ERRO] => operation INCLUI_BOLETO not present in WSDL.`

Mas consultando o WSDL vejo que está presente.
OBS: Conforme a sugestão de @vmassuchetto, copiei o WSDL disponível em [https://des.barramento.caixa.gov.br/sibar/ManutencaoCobrancaBancaria/Boleto?wsdl](url)
Porém dentro do arquivo alterei para as urls removendo o "des." conforme sujestão de @wagnermengue (foi o único jeito de fazer funcionar).

E novamente, valeu pessoal.

**Comment by tiagojoelbackes** [comment]
Segue abaixo o conteúdo do debug. Desde já agradeço.

`
[debug] => Array
        (
            [RETORNO_CAIXA] => Array
                (
                    [0] => Array
                        (
                            [ERRO] => 
                            [RESPOSTA] => HTTP/1.1 100 Continue

HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 19:15:59 GMT
Server: SIBAR.SP.SPPFCJD2
Content-Type: text/xml;charset=iso-8859-1
Content-Length: 1110
Connection: close

<?xml version="1.0" encoding="iso-8859-1"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
<soapenv:Body>
<consultacobrancabancaria:SERVICO_SAIDA xmlns:consultacobrancabancaria="http://caixa.gov.br/sibar/consulta_cobranca_bancaria/boleto" xmlns:sibar_base="http://caixa.gov.br/sibar">
<sibar_base:HEADER>
<VERSAO>1.0</VERSAO>
<AUTENTICACAO>####removido###</AUTENTICACAO>
<USUARIO_SERVICO>SGCBS02P</USUARIO_SERVICO>
<OPERACAO>CONSULTA_BOLETO</OPERACAO>
<SISTEMA_ORIGEM>SIGCB</SISTEMA_ORIGEM>
<UNIDADE>####removido###</UNIDADE>
<IDENTIFICADOR_ORIGEM>####removido###</IDENTIFICADOR_ORIGEM>
<DATA_HORA>20180104171552</DATA_HORA>
<ID_PROCESSO></ID_PROCESSO>
</sibar_base:HEADER>
<COD_RETORNO>00</COD_RETORNO>
<ORIGEM_RETORNO>CONSULTA_COBRANCA_BANCARIA</ORIGEM_RETORNO>
<MSG_RETORNO></MSG_RETORNO>
<DADOS>
<CONTROLE_NEGOCIAL>
<ORIGEM_RETORNO>SIGCB</ORIGEM_RETORNO>
<COD_RETORNO>1</COD_RETORNO>
<MENSAGENS>
<RETORNO>(47) NOSSO NUMERO NAO CADASTRADO PARA O BENEFICIARIO</RETORNO>
</MENSAGENS>
</CONTROLE_NEGOCIAL>
</DADOS>
</consultacobrancabancaria:SERVICO_SAIDA>
</soapenv:Body>
</soapenv:Envelope>
                        )

                    [1] => Array
                        (
                            [ERRO] => wsdl error: Getting https://barramento.caixa.gov.br/sibar/ManutencaoCobrancaBancaria/Boleto?xsd=xsd0 - HTTP ERROR: Unsupported HTTP response status 404 Not Found (soapclient->response has contents of the response)
                            [RESPOSTA] => 
                        )

                    [2] => Array
                        (
                            [ERRO] => operation INCLUI_BOLETO not present in WSDL.
                            [RESPOSTA] => 
                        )

                )

        )
`

**Comment by vmassuchetto** [comment]
@tiagojoelbackes coloquei algumas orientações para baixar e substituir os arquivos [aqui](https://github.com/vmassuchetto/WebserviceCaixa/blob/master/README.md#modo-de-uso).

Dá uma olhada e vê se ajuda.

**Comment by tiagojoelbackes** [comment]
Olá @vmassuchetto . Segui as instruções que vc disponibilizou, muito obrigado.
Os arquivos EmiteBoleto.xsd e MensagensBarramento.xsd vc não informou como pegá-los, mas eu tinha eles disponibilizados pela caixa, então tentei com eles.
Novamente precisei utilizar a URL de produção, pois dev está dando usuário não autorizado.

O resultado que tive foi o mesmo, continua retornando `[ERRO] => operation INCLUI_BOLETO not present in WSDL.`

Já esgotei minhas alternativas, não sei o que pode ser. Várias vezes tentei contato com o suporte da caixa, mas é inútil.

:'(

**Comment by wagnermengue** [comment]
Olá @tiagojoelbackes , depois de já ter finalizado meu projeto obtive uma informação, vejas se consegue realizar o teste enviando o parâmetro:
Ao invés de passar assim: 
`<USUARIO_SERVICO>SGCBS02P</USUARIO_SERVICO>`
Passe assim:
`<USUARIO_SERVICO>SGCBS01D</USUARIO_SERVICO>`

Parece que quando enviado esse 01D (indica desenvolvimento) e 02P (indica produção)

Mas ai acredito que terias de validar qual url para mandar, usar o subdomínio 'des' antes.

Att,

**Comment by tiagojoelbackes** [comment]
WOW!!!
De fato, `<USUARIO_SERVICO>SGCBS02P</USUARIO_SERVICO>`  é para as URLs de produção e `<USUARIO_SERVICO>SGCBS01D</USUARIO_SERVICO>` para as URLs de desenvolvimento.

Valeu pela dica!

Fiz o teste na URL de desenvolvimento com o usuário 01D e mudou o ERRO.
Retornou `(89) OPERACAO NAO PERMITIDA - CEDENTE INFORMADO NAO POSSUI AUTORIZACAO PARA UTILIZAR SERVICO WEBSERVICE`.
O engraçado é que na produção permite consulta. Talvez seja aquilo que você falou na primeira resposta de que uma vez habilitado em produção não é possível utilizar em desenvolvimento.

Infelizmente, em produção, o erro `[ERRO] => operation INCLUI_BOLETO not present in WSDL.` reportado por mim acima ainda permanece. Chegou a passar por ele @wagnermengue ?

:'(

**Comment by wagnermengue** [comment]
@tiagojoelbackes não passei por ele, pois chamo o método diretamente da url deles, eu montei uma API separada para fazer as chamadas de forma mais simples, sem necessitar do soap.

**Comment by tiagojoelbackes** [comment]
Como assim @wagnermengue ?
Não faço questão de usar soap, estou usando pois achei que era a única alternativa. O importante pra mim é o objetivo final nesse momento, que é o de registrar os boletos em tempo real.
Você poderia me dar mais detalhes dessa sua abordagem? Ficaria deveras agradecido.

**Comment by wagnermengue** [comment]
Opa, claro @tiagojoelbackes , vou extrair do meu projeto de forma genérica e postar no meu github, acredito que nesse final de semana eu consiga fazer, ai lhe aviso por aqui.

**Comment by tiagojoelbackes** [comment]
Ok amigo, fico ansiosamente no aguardo :)

**Comment by wagnermengue** [comment]
Olá @tiagojoelbackes , fiz de forma bem simplificada para que possas fazer os testes. Segue o repo:

https://github.com/wagnermengue/caixa-webservice

Att,

**Comment by tiagojoelbackes** [comment]
Bom dia @wagnermengue , muito obrigado pela força!!!
Vou testar imediatamente.

**Comment by vmassuchetto** [comment]
Valeu @wagnermengue.

**Comment by r-guimaraes** [comment]
@tiagojoelbackes seus testes deram certo?

**Comment by tiagojoelbackes** [comment]
Olá @r-guimaraes deram certo sim.

**Comment by r-guimaraes** [comment]
Maravilha @tiagojoelbackes . Vc utilizou este repositório aqui mesmo?

**Comment by tiagojoelbackes** [comment]
Acabei por utilizar a solução do @wagnermengue . Ainda estou implementando meu sistema na verdade, mas já consegui registrar e consultar boletos.

**Comment by r-guimaraes** [comment]
Tá ótimo. Muito obrigado pelo feedback @tiagojoelbackes

**Comment by Wendool** [comment]
Bom dia, @tiagojoelbackes poderia compartilhar o codigo com sucesso no registro e consulta? 
O meu esta apresentando a seguinte mensagem.

Array
(
    [EXCECAO] => EXCECAO NO BAR_MANUTENCAO_COBRANCA_BANCARIA_WS.SOAPInput_Empresas_Externas. DETALHES: ParserException(1) - Funcao: ImbDataFlowNode::createExceptionList, Texto Excecao: Node throwing exception, Texto de Insercao(1) - BAR_MANUTENCAO_COBRANCA_BANCARIA_WS.SOAPInput_Empresas_Externas.ParserException(2) - Funcao: ImbSOAPInputNode::validateData, Texto Excecao: Error occurred in ImbSOAPInputHelper::validateSOAPInput(), Texto de Insercao(1) - BAR_MANUTENCAO_COBRANCA_BANCARIA_WS.SOAPInput_Empresas_Externas.ParserException(3) - Funcao: ImbRootParser::parseNextItem, Texto Excecao: Exception whilst parsing.ParserException(4) - Funcao: ImbSOAPParser::createSoapShapedTree, Texto Excecao: problem creating SOAP tree from bitstream.ParserException(5) - Funcao: ImbXMLNSCParser::parseLastChild, Texto Excecao: XML Parsing Errors have occurred.ParserException(6) - Funcao: ImbXMLNSCDocHandler::handleParseErrors, Texto Excecao: A schema validation error has occurred while parsing the XML document, Texto de Insercao(1) - 6000, Texto de Insercao(2) - 1, Texto de Insercao(3) - 27, Texto de Insercao(4) - 28, Texto de Insercao(5) - cvc-datatype-valid.1.2: The value "" is not a valid value for the "date" datatype., Texto de Insercao(6) - /XMLNSC/{http://schemas.xmlsoap.org/soap/envelope/}:Envelope/{http://schemas.xmlsoap.org/soap/envelope/}:Body/{http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo}:SERVICO_ENTRADA/DADOS/INCLUI_BOLETO/TITULO/JUROS_MORA/DATA.
)

**Comment by tiagojoelbackes** [comment]
Esse erro provavelmente está ocorrendo pois está passando uma data vazia na requisição.
Veja se está passando o vencimento corretamente.

**Comment by Wendool** [comment]
Bom dia @tiagojoelbackes , tentei de varias formas não sai o erro,  segue as duas formas,
   public $dataVencimento = '20180529';
   public $dataEmissao = '20180528';
ou
   public $dataVencimento = '2018-05-29';
   public $dataEmissao = '2018-05-28';



Array
(
    [EXCECAO] => EXCECAO NO BAR_MANUTENCAO_COBRANCA_BANCARIA_WS.SOAPInput_Empresas_Externas. DETALHES: ParserException(1) - Funcao: ImbDataFlowNode::createExceptionList, Texto Excecao: Node throwing exception, Texto de Insercao(1) - BAR_MANUTENCAO_COBRANCA_BANCARIA_WS.SOAPInput_Empresas_Externas.ParserException(2) - Funcao: ImbSOAPInputNode::validateData, Texto Excecao: Error occurred in ImbSOAPInputHelper::validateSOAPInput(), Texto de Insercao(1) - BAR_MANUTENCAO_COBRANCA_BANCARIA_WS.SOAPInput_Empresas_Externas.ParserException(3) - Funcao: ImbRootParser::parseNextItem, Texto Excecao: Exception whilst parsing.ParserException(4) - Funcao: ImbSOAPParser::createSoapShapedTree, Texto Excecao: problem creating SOAP tree from bitstream.ParserException(5) - Funcao: ImbXMLNSCParser::parseLastChild, Texto Excecao: XML Parsing Errors have occurred.ParserException(6) - Funcao: ImbXMLNSCDocHandler::handleParseErrors, Texto Excecao: A schema validation error has occurred while parsing the XML document, Texto de Insercao(1) - 6000, Texto de Insercao(2) - 1, Texto de Insercao(3) - 27, Texto de Insercao(4) - 28, Texto de Insercao(5) - cvc-datatype-valid.1.2: The value "" is not a valid value for the "date" datatype., Texto de Insercao(6) - /XMLNSC/{http://schemas.xmlsoap.org/soap/envelope/}:Envelope/{http://schemas.xmlsoap.org/soap/envelope/}:Body/{http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo}:SERVICO_ENTRADA/DADOS/INCLUI_BOLETO/TITULO/JUROS_MORA/DATA.
)

**Comment by tiagojoelbackes** [comment]
Blz. Ponha aqui o xml que vc está enviando.

**Comment by Wendool** [comment]
array(1) {
  ["soapenv:Body"]=>
  array(1) {
    ["manutencaocobrancabancaria:SERVICO_ENTRADA"]=>
    array(2) {
      ["sibar_base:HEADER"]=>
      array(7) {
        ["VERSAO"]=>
        string(3) "1.0"
        ["AUTENTICACAO"]=>
        string(44) "QrNA9gliZBBXi4GESZHRkTVTn+iaHmd0AcekI9eq524="
        ["USUARIO_SERVICO"]=>
        string(8) "SGCBS01D"
        ["OPERACAO"]=>
        string(13) "INCLUI_BOLETO"
        ["SISTEMA_ORIGEM"]=>
        string(5) "SIGCB"
        ["UNIDADE"]=>
        string(4) "3569"
        ["DATA_HORA"]=>
        string(14) "20180528115018"
      }
      ["DADOS"]=>
      array(1) {
        ["INCLUI_BOLETO"]=>
        array(2) {
          ["CODIGO_BENEFICIARIO"]=>
          string(6) "730502"
          ["TITULO"]=>
          array(14) {
            ["NOSSO_NUMERO"]=>
            string(17) "00000000000400001"
            ["NUMERO_DOCUMENTO"]=>
            string(6) "400001"
            ["DATA_VENCIMENTO"]=>
            string(10) "2018-05-29"
            ["VALOR"]=>
            string(15) "000000000002490"
            ["TIPO_ESPECIE"]=>
            string(2) "99"
            ["FLAG_ACEITE"]=>
            string(1) "S"
            ["DATA_EMISSAO"]=>
            string(10) "2018-05-28"
            ["JUROS_MORA"]=>
            array(3) {
              ["TIPO"]=>
              string(11) "TAXA_MENSAL"
              ["DATA"]=>
              string(0) ""
              ["PERCENTUAL"]=>
              string(0) ""
            }
            ["VALOR_ABATIMENTO"]=>
            string(1) "0"
            ["POS_VENCIMENTO"]=>
            array(2) {
              ["ACAO"]=>
              string(8) "DEVOLVER"
              ["NUMERO_DIAS"]=>
              string(2) "90"
            }
            ["CODIGO_MOEDA"]=>
            string(2) "09"
            ["PAGADOR"]=>
            array(3) {
              ["CPF"]=>
              string(11) "06474817909"
              ["NOME"]=>
              string(13) "Wendool Souza"
              ["ENDERECO"]=>
              array(5) {
                ["LOGRADOURO"]=>
                string(17) "R Alvin Bauer 523"
                ["BAIRRO"]=>
                string(6) "Centro"
                ["CIDADE"]=>
                string(20) "BalneÃ¡rio CamboriÃº"
                ["UF"]=>
                string(2) "SC"
                ["CEP"]=>
                string(9) "88330-643"
              }
            }
            ["MULTA"]=>
            array(2) {
              ["DATA"]=>
              string(0) ""
              ["PERCENTUAL"]=>
              string(0) ""
            }
            ["DESCONTOS"]=>
            array(0) {
            }
          }
        }
      }
    }
  }
}

**Comment by Wendool** [comment]
array(1) {
  ["soapenv:Body"]=>
  array(1) {
    ["manutencaocobrancabancaria:SERVICO_ENTRADA"]=>
    array(2) {
      ["sibar_base:HEADER"]=>
      array(7) {
        ["VERSAO"]=>
        string(3) "1.0"
        ["AUTENTICACAO"]=>
        string(44) "QrNA9gliZBBXi4GESZHRkTVTn+iaHmd0AcekI9eq524="
        ["USUARIO_SERVICO"]=>
        string(8) "SGCBS01D"
        ["OPERACAO"]=>
        string(13) "INCLUI_BOLETO"
        ["SISTEMA_ORIGEM"]=>
        string(5) "SIGCB"
        ["UNIDADE"]=>
        string(4) "3569"
        ["DATA_HORA"]=>
        string(14) "20180528115221"
      }
      ["DADOS"]=>
      array(1) {
        ["INCLUI_BOLETO"]=>
        array(2) {
          ["CODIGO_BENEFICIARIO"]=>
          string(6) "730502"
          ["TITULO"]=>
          array(14) {
            ["NOSSO_NUMERO"]=>
            string(17) "00000000000400001"
            ["NUMERO_DOCUMENTO"]=>
            string(6) "400001"
            ["DATA_VENCIMENTO"]=>
            string(10) "2018-05-29"
            ["VALOR"]=>
            string(15) "000000000002490"
            ["TIPO_ESPECIE"]=>
            string(2) "99"
            ["FLAG_ACEITE"]=>
            string(1) "S"
            ["DATA_EMISSAO"]=>
            string(10) "2018-05-28"
            ["JUROS_MORA"]=>
            array(3) {
              ["TIPO"]=>
              string(11) "TAXA_MENSAL"
              ["DATA"]=>
              string(0) ""
              ["PERCENTUAL"]=>
              string(0) ""
            }
            ["VALOR_ABATIMENTO"]=>
            string(1) "0"
            ["POS_VENCIMENTO"]=>
            array(2) {
              ["ACAO"]=>
              string(8) "DEVOLVER"
              ["NUMERO_DIAS"]=>
              string(2) "90"
            }
            ["CODIGO_MOEDA"]=>
            string(2) "09"
            ["PAGADOR"]=>
            array(3) {
              ["CPF"]=>
              string(11) "99163070758"
              ["NOME"]=>
              string(13) "Wendool Souza"
              ["ENDERECO"]=>
              array(5) {
                ["LOGRADOURO"]=>
                string(13) "R Alvin Bauer"
                ["BAIRRO"]=>
                string(6) "Centro"
                ["CIDADE"]=>
                string(20) "BalneÃ¡rio CamboriÃº"
                ["UF"]=>
                string(2) "SC"
                ["CEP"]=>
                string(9) "88330-643"
              }
            }
            ["MULTA"]=>
            array(2) {
              ["DATA"]=>
              string(0) ""
              ["PERCENTUAL"]=>
              string(0) ""
            }
            ["DESCONTOS"]=>
            array(0) {
            }
          }
        }
      }
    }
  }
}

**Comment by tiagojoelbackes** [comment]
XML por favor. Fica mais fácil analisarmos. Mas antes faça um teste garantindo os dados que está passando para juro e multa. Vejo que há inconsistência de datas aí.

**Comment by Wendool** [comment]
Boa tarde @tiagojoelbackes, entrei em contato com o gerente ainda não tinha sido liberado a parte de produção por eles, hoje ocorreu.
Agora o erro mudou para o seguinte:
[RETORNO] => (54) OPERACAO NAO PERMITIDA - HASH DIVERGENTE

 public $urlIntegracao = 'https://barramento.caixa.gov.br/sibar/ManutencaoCobrancaBancaria/Boleto/Externo';
    public $codigoCedente = '730502'; //cedente ou beneficiário
    public $nossoNumero = '00000000000000000';
    public $dataVencimento = '2018-06-28';
    public $valorNominal = '000000000002490';
    public $cnpj = '07473225000104';
    public $codigoTitulo = '400001';
    public $dataEmissao = '2018-06-04';

    public $dataJuros = '2018-06-29';
    public $juros = '0.33';

    public $dataMulta = '2018-06-29';
    public $multa = '2.00';

    public $numeroAgencia = '3569';


O que pode estar errado para não gerar corretamente?

**Comment by Wendool** [comment]
Boa tarde pessoal,

Estou enviado remessa para a caixa e nos trabalhamos com desconto até dia 07 de cada mês de 50,00 com isso tento enviar para o para a caixa o valor e o registra com desconto, o que pode ser?


$arrayDados = array(
				'soapenv:Body' => array(
					'manutencaocobrancabancaria:SERVICO_ENTRADA' => array(
						'sibar_base:HEADER' => array(
								'VERSAO' => '1.0',
								'AUTENTICACAO' => $autenticacao,
								'USUARIO_SERVICO' => 'SGCBS02P', //SGCBS02P - Produção | SGCBS01D - Desenvolvimento
								'OPERACAO' => 'INCLUI_BOLETO', //Implementado apenas para inclusão
								'SISTEMA_ORIGEM' => 'SIGCB',
								'UNIDADE' => $informacoes['numeroAgencia'],
								'DATA_HORA' => date('YmdHis')
						),
						'DADOS' => array(
								'INCLUI_BOLETO' => array(
										'CODIGO_BENEFICIARIO' => $informacoes['codigoCedente'],
										'TITULO' => array(
												'NOSSO_NUMERO' => $informacoes['nossoNumero'],
												'NUMERO_DOCUMENTO' => $informacoes['codigoTitulo'], //código interdo do boleto/título
												'DATA_VENCIMENTO' => $informacoes['dataVencimento'],
												'VALOR' => $informacoes['valorNominal'],
												'TIPO_ESPECIE' => '02', // Olhar no manual qual enviar
												'FLAG_ACEITE' => 'S', // S-Aceite | N-Não aceite (reconhecimento de dívida pelo pagador)
												'DATA_EMISSAO' => $informacoes['dataEmissao'],
												'JUROS_MORA' => array(
														'TIPO' => 'TAXA_MENSAL',
														'DATA' => $informacoes['dataJuros'],
														'PERCENTUAL' => $informacoes['juros'],
												),
												'VALOR_ABATIMENTO' => '0',
												'POS_VENCIMENTO' => array(
														'ACAO' => 'DEVOLVER',
														'NUMERO_DIAS' => '30',
												),
												'DESCONTOS' => array(
													'DESCONTO' => array(
															'DATA' => $desconto['dataValidade'],
															'VALOR' => $desconto['valor'],
													)
												),
												'CODIGO_MOEDA' => '09', //Real
												'PAGADOR' => $informacoes['infoPagador'],
												'MULTA' => array(
														'DATA' => $informacoes['dataMulta'],
														'PERCENTUAL' => $informacoes['multa'],
												),
											
										)
								)
						)
					)
				)
		);

**Comment by DaviFrazao** [comment]
Olá, alguém poderia me informar onde consigo o EmiteBoleto.xsd e o MensagemBarramento.xsd? Preciso urgente para uma aplicação, mas a caixa não me dá o retorno dos arquivos.

**Comment by braynerdev** [comment]
o USUARIO_SERVICO de desenvolvimento ainda esta funcionando? pois fica dando esse erro "(
CI10) TRANSACAO TEMPORARIAMENTE INDISPONIVEL.</MSG_RETORNO><DADOS><EXCECAO>CicsAbend: AEI0 PROGRAMA DESABILITADO OU INEXISTENTE NO CICS DO BARRAMENTO OU CICS REMOTO."
