### ISSUE TITLE
Parâmetro USUARIO_SERVICO para desenvolvimento e produção

### ISSUE THREAD

**Issue by vmassuchetto** [vmassuchetto/WebserviceCaixa#7]
Variar o parêmetro conforme ambiente. Identificado em https://github.com/vmassuchetto/WebserviceCaixa/issues/5#issuecomment-355601747

> Ao invés de passar assim:
> 
>     <USUARIO_SERVICO>SGCBS02P</USUARIO_SERVICO>
> 
> Passe assim:
>         
>     <USUARIO_SERVICO>SGCBS01D</USUARIO_SERVICO>
>
> Parece que quando enviado esse 01D (indica desenvolvimento) e 02P (indica produção)

**Comment by vmassuchetto** [comment]
Isto foi feito em 74ccda278814086aa03568835417433cc82a8da1.

**Comment by JNNelson** [comment]
@vmassuchetto 
Ola. Nao achei outro local mais correto para postar ja que a maioria sao topicos antigos. A pergunta é onde encontro os manuais da CEF referente ao webservice? E com quem meu cliente solicita esta opcao na caixa, ja que o gerente PJ dele desconhece o assunto e nem no proprio site da Caixa tem informacoes a respeito.
