### ISSUE TITLE
2ª via boleto

### ISSUE THREAD

**Issue by tiagojoelbackes** [vmassuchetto/WebserviceCaixa#8]
A dúvida que tenho não necessariamente está relacionada ao sistema, mas sim, ao processo.
Vi que no ws existem métodos para registro, alteração e baixa de boleto.
Estou implementado meu sistema para eu mesmo gerar o layout do boleto e para tal estou adaptando o boletophp.
Minha dúvida é a seguinte, caso eu queira disponibilizar uma segunda via em meu próprio ambiente, necessito realizar alguma transação via ws para atualizar?
Pergunto pois estava olhando os boletos gerados pela própria caixa, que devolvem em um link na requisição de consulta. Os boletos vencidos vinham com a seguinte mensagem:

> PARA EMISSAO DE 2° VIA ACESSE BLOQUETOEXPRESSO.CAIXA.GOV.BR

De fato acessei e gerei na página da caixa a segunda via, a questão é que somente após eu ter feito isso o boleto devolvido pelo ws da caixa veio atualizado para pagamento na data atual.

Alguém tem alguma sugestão?

**Comment by denisdemaisbr** [comment]
@tiagojoelbackes eu ainda não li a documentação, mas, você pode opcionalmente manter uma cópia no servidor (arquivo xml ou pdf) para uso futuro e ir 'limpando' isso após o vencimento e/ou periodicamente.

**Comment by vmassuchetto** [comment]
@tiagojoelbackes quando o boleto vence nós geramos uma "segunda via" através da alteração do nosso número, data de validade e valor com juros. Para cada alteração dessas pagamos uma taxa.

**Comment by vmassuchetto** [comment]
Fechando aqui @tiagojoelbackes. Espero que tenha resolvido.
